function Fmodeplatplot(modes, rawplateau,fittedplateau)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 03-Nov-2017 11:50:17

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create loglog
loglog(modes,rawplateau,'MarkerFaceColor',[0 0.447058826684952 0.74117648601532],...
    'Marker','o',...
    'LineWidth',2,...
    'LineStyle','--');

% Create loglog
loglog(modes(1:length(fittedplateau)),fittedplateau,'LineWidth',2);

% Create xlabel
xlabel('Wavevector, q (\mum^-^1)');

% Create ylabel
ylabel('MSD plateau (um)');

% Set the remaining axes properties
set(axes1,'FontSize',20,'XMinorTick','on','XScale','log','YMinorTick','on',...
    'YScale','log');
