function FmodeMSDplot(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 03-Nov-2017 11:44:56

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to loglog
loglog(X1,YMatrix1,'Parent',axes1,'LineWidth',3);

% Create xlabel
xlabel('lag time (s)');

% Create ylabel
ylabel('MSD (um)');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0.009 25]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[-Inf Inf]);
% Set the remaining axes properties
set(axes1,'FontSize',20,'XMinorTick','on','XScale','log','YMinorTick','on',...
    'YScale','log');
