function linlogmsdplot(msd)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 09-Nov-2017 11:14:32

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create semilogx
semilogx(msd);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XMinorTick','on','XScale','log');
