function pltflopmds(lag, data,names)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
X1 = lag;
YMatrix1 = data;
%  Auto-generated by MATLAB on 15-Nov-2017 14:46:15

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
for k = 1:size(YMatrix1,1)
    set(plot1(k),'DisplayName',names{k});
end

% Create xlabel
xlabel('Lag time (s)');

% Create ylabel
ylabel('Correlation (um)');

xlim(axes1,[-20 20]);
% Set the remaining axes properties
set(axes1,'FontSize',20,'YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.819485658803692 0.154142592008977 0.0727002956968033 0.232658952862197],...
    'EdgeColor',[1 1 1]);

